namespace Emotions.FACS
{
    /// <summary>
    /// Source https://en.wikipedia.org/wiki/Facial_Action_Coding_System
    /// </summary>
    enum ActionUnits
    {
        // Main Codes
        NeutralFace = 0,
        InnerBrowRaiser = 1,
        OuterBrowRaiser = 2,
        BrowLowerer = 4,
        UpperLidRaiser = 5,
        CheekRaiser = 6,
        LidTightener = 7,
        LipsTowardEachOther = 8,
        NoseWrinkler = 9,
        UpperLipRaiser = 10,
        NasolabialDeepener = 11,
        LipCornerPuller = 12,
        SharpLipPuller = 13,
        Dimpler = 14,
        LipCornerDepressor = 15,
        LowerLipDepressor = 16,
        ChinRaiser = 17,
        LipPucker = 18,
        TongueShow = 19,
        LipStretcher = 20,
        NeckTightener = 21,
        LipFunneler = 22,
        LipTightener = 23,
        LipPressor = 24,
        LipsPart = 25,
        JawLowerer = 26,
        MouthStretch = 27,
        LipSuck = 28,
        JawThrust = 29,
        JawSideways = 30,
        JawClencher = 31,
        LipBite = 32,
        CheekBlow = 33,
        CheekPuff = 34,
        CheekSuck = 35,
        TongueBulge = 36,
        LipWipe = 37,
        NostrilDilator = 38,
        NostrilCompressor = 39,
        GlabellaLowerer = 41,
        InnerEyebrowLowerer = 42,
        EyesClosed = 43,
        EyebrowGatherer = 44,
        Blink = 45,
        Wink = 46,

        // Head Movement Codes
        HeadTurnLeft = 51,
        HeadTurnRight = 52,
        HeadUp = 53,
        HeadDown = 54,
        HeadTiltLeft = 55,
        HeadTiltRight = 56,
        HeadForward = 57,
        HeadBack = 58,
        HeadShakeUpAndDown = 59,
        HeadShakeSideToSide = 60,
        HeadUpwardAndToTheSide = 83,

        // Eye Movement Codes
        EyesTurnLeft = 61,
        EyesTurnRight = 62,
        EyesUp = 63,
        EyesDown = 64,
        Walleye = 65,
        CrossEye = 66,
        UpwardRollingOfEyes = 68,
        EyesPositionedToLookAtOtherPerson = 69,

        // Visibility Codes
        BrowsAndForeheadNotVisible = 70,
        EyesNotVisible = 71,
        LowerFaceNotVisible = 72,
        EntireFaceNotVisible = 73,
        Unscorable = 74,

        // Gross Behavior Codes
        Sniff = 40,
        Speech = 50,
        Swallow = 80,
        Chewing = 81,
        ShoulderShrug = 82,
        HeadShakeBackAndForth = 84,
        HeadNodUpAndDown = 85,
        Flash = 91,
        PartialFlash = 92,
        ShiverOrTremble = 97,
        FastUpDownLook = 98,
    }
}
